Repository solidjs-community/solid-primitives, pull requests merged in 2022-06, with the labels that each got.

#154 add `keyboard` package with `makeKeyHoldListener`
  packages/keyboard/LICENSE
  packages/keyboard/README.md
  packages/keyboard/dev/index.html
  packages/keyboard/dev/index.tsx
  packages/keyboard/dev/vite.config.ts
  packages/keyboard/package.json
  packages/keyboard/src/env.d.ts
  packages/keyboard/src/holdKeyListener.ts
  packages/keyboard/src/index.ts
  packages/keyboard/src/server.ts
  packages/keyboard/test/index.test.ts
  packages/keyboard/tsconfig.json
  packages/keyboard/tsup.config.ts
Labels: Primitive Proposal

#125 Geolocation: Minor improvements and test updates
  packages/geolocation/README.md
  packages/geolocation/dev/index.html
  packages/geolocation/dev/index.tsx
  packages/geolocation/dev/vite.config.ts
  packages/geolocation/package.json
  packages/geolocation/src/index.ts
  packages/geolocation/src/server.ts
  packages/geolocation/test/index.test.ts
  packages/geolocation/test/setup.ts
Labels: enhancement

#124 Clipboard: Adapt to new `make` pattern + improve tests
  packages/clipboard/README.md
  packages/clipboard/dev/img.png
  packages/clipboard/dev/img2.png
  packages/clipboard/dev/index.html
  packages/clipboard/dev/index.tsx
  packages/clipboard/package.json
  packages/clipboard/src/index.ts
  packages/clipboard/src/server.ts
  packages/clipboard/src/types.d.ts
  packages/clipboard/test/index.test.ts
  packages/clipboard/test/setup.ts
  packages/intersection-observer/dev/vite.config.ts.js
Labels: refactor
